[phases.setup]
nixPkgs = ['nodejs', 'npm', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = [
  'npm ci',
  'npm rebuild better-sqlite3 --build-from-source'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
